### STADIUMS INDEX
GET http://localhost:3000/stadiums.json

### STADIUMS SHOW
GET http://localhost:3000/stadiums/8.json

### STADIUMS CREATE
POST http://localhost:3000/stadiums.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE3MTU5Mzl9.LsWXFoegucW4u5q0vQ3XkYM452u4o-56yxDMrugHVpg
Content-Type: application/json

{
   "name": "Gillette Stadium", "city": "Foxborough", "address": "1 Patriot Pl, Foxborough, MA 02035", "image": "https://assets2.cbsnewsstatic.com/hub/i/r/2019/07/10/d09559ef-c1f3-482a-84c2-57e21db7be0f/thumbnail/1200x630/92723d760c8738d335e37d2fb34ba27d/gilette.jpg"
}


### STADIUMS UPDATE
PATCH http://localhost:3000/stadiums/8.json
Content-Type: application/json

{
   "image": "https://frontofficesports.com/wp-content/uploads/2022/01/FOS-Saturday-SoFi-Stadium-2.jpg"
}

### STADIUMS DELETE
DELETE http://localhost:3000/stadiums/21.json




### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}
