### STADIUMS INDEX
GET http://localhost:3000/stadiums.json

### STADIUMS SHOW
GET http://localhost:3000/stadiums/8.json

### STADIUMS CREATE
POST http://localhost:3000/stadiums.json
Content-Type: application/json

{
   "name": "Lumen Field", "city": "Seattle", "address": "", "image": ""
}


### STADIUMS UPDATE
PATCH http://localhost:3000/stadiums/8.json
Content-Type: application/json

{
   "image": "https://frontofficesports.com/wp-content/uploads/2022/01/FOS-Saturday-SoFi-Stadium-2.jpg"
}

### STADIUMS DELETE
DELETE http://localhost:3000/stadiums/18.json




### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}
